[WIP] Atualizar Documento de Visão
fga-eps-mds/2020.2-e-Vacina-Backend pull request #75
Opened 2021-03-11 14:08 UTC by yesklin

### Descrição
Atualiza o documento de visão.

### Porque este Pull Request é necessário?
Para guiar os desenvolvedores e apresentar a ideia do projeto.

Resolve #39.

2021-03-11 23:24 UTC, GRVial requested changes
Consertar algumas coisinhas e fica beleza.

2021-03-11 23:24 UTC, GRVial commented on docs/wiki/documento_visao.md
> -Atualmente, os brasileiro possuem a carteira de vacina física, que está sujeita a perdas, deterioração e rasuras, essa é a única forma oficial de fazer controle de vacinação individual. Algumas empre
os brasileiros

2021-03-11 23:24 UTC, GRVial commented on docs/wiki/documento_visao.md
> +Este documento tem como propósito apresentar o aplicativo e-Vacina: uma carteira digital de vacinão. Além disso, também serão apresentados seus requisitos funcionais, não-funcionais e diagramas. Por
funcionais e não funcionais e diagramas.

2021-03-11 23:24 UTC, GRVial commented on docs/wiki/documento_visao.md
> +Inicialmente, o usuário deverá ser registrar informando seus dados: nome, cidade, idade, sexo, ect.
se registrar

2021-03-11 23:24 UTC, GRVial commented on docs/wiki/documento_visao.md
> -|   |   |   |   |
adicionar nova versão com mudanças

2021-03-11 23:30 UTC, GRVial commented on docs/wiki/documento_visao.md
> +Atualmente, os brasileiro possuem a carteira de vacina física, que está sujeita a perdas, deterioração e rasuras, essa é a única forma oficial de fazer controle de vacinação individual. Algumas empre
como a Pfizer

2021-03-12 00:02 UTC, yesklin commented on docs/wiki/documento_visao.md
> +Este documento tem como propósito apresentar o aplicativo e-Vacina: uma carteira digital de vacinão. Além disso, também serão apresentados seus requisitos funcionais, não-funcionais e diagramas. Por
Eu acho que o correto seria vírgula.

2021-03-12 00:15 UTC, GRVial commented on docs/wiki/documento_visao.md
> +Este documento tem como propósito apresentar o aplicativo e-Vacina: uma carteira digital de vacinão. Além disso, também serão apresentados seus requisitos funcionais, não-funcionais e diagramas. Por
Mas ai parece que diagramas é um requisito.

2021-03-12 00:17 UTC, GRVial commented on docs/wiki/documento_visao.md
> +Este documento tem como propósito apresentar o aplicativo e-Vacina: uma carteira digital de vacinão. Além disso, também serão apresentados seus requisitos funcionais, não-funcionais e diagramas. Por
Pode ser "requisitos funcionais, requisitos não funcionais e diagramas".

2021-03-12 00:19 UTC, merged